import { Platform } from 'react-native';

export const Colors = {
  light: {
    background: '#ffffff',
    foreground: '#171717',
    card: '#ffffff',
    cardForeground: '#171717',
    popover: '#ffffff',
    popoverForeground: '#171717',
    primary: '#262626',
    primaryForeground: '#fafafa',
    secondary: '#f5f5f5',
    secondaryForeground: '#262626',
    muted: '#f5f5f5',
    mutedForeground: '#737373',
    accent: '#f5f5f5',
    accentForeground: '#262626',
    destructive: '#dc2626',
    destructiveForeground: '#fafafa',
    success: '#16a34a',
    successForeground: '#f0fdf4',
    border: '#e5e5e5',
    input: '#e5e5e5',
    ring: '#a3a3a3',
    text: '#171717',
    tint: '#262626',
    icon: '#737373',
    tabIconDefault: '#737373',
    tabIconSelected: '#262626',
  },
  dark: {
    background: '#171717',
    foreground: '#fafafa',
    card: '#262626',
    cardForeground: '#fafafa',
    popover: '#333333',
    popoverForeground: '#fafafa',
    primary: '#e5e5e5',
    primaryForeground: '#262626',
    secondary: '#333333',
    secondaryForeground: '#fafafa',
    muted: '#333333',
    mutedForeground: '#a3a3a3',
    accent: '#404040',
    accentForeground: '#fafafa',
    destructive: '#f87171',
    destructiveForeground: '#dc2626',
    success: '#22c55e',
    successForeground: '#14532d',
    border: 'rgba(255, 255, 255, 0.1)',
    input: 'rgba(255, 255, 255, 0.15)',
    ring: '#737373',
    text: '#fafafa',
    tint: '#e5e5e5',
    icon: '#a3a3a3',
    tabIconDefault: '#a3a3a3',
    tabIconSelected: '#e5e5e5',
  },
};

export const Radius = {
  none: 0,
  sm: 6,
  md: 8,
  DEFAULT: 10,
  lg: 10,
  xl: 14,
  '2xl': 18,
  '3xl': 22,
  full: 9999,
};

export const Typography = {
  default: { fontSize: 16, lineHeight: 24 },
  defaultSemiBold: { fontSize: 16, lineHeight: 24, fontWeight: '600' as const },
  title: { fontSize: 32, fontWeight: 'bold' as const, lineHeight: 32 },
  subtitle: { fontSize: 20, fontWeight: 'bold' as const },
  link: { lineHeight: 30, fontSize: 16 },
};

export const Fonts = Platform.select({
  ios: { sans: 'system-ui', serif: 'ui-serif', rounded: 'ui-rounded', mono: 'ui-monospace' },
  default: { sans: 'normal', serif: 'serif', rounded: 'normal', mono: 'monospace' },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
